modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/lehjr/MPA-Lib/issues"

[[mods]]
    modId="mpalib"
    version="${file.jarVersion}"
    displayName="MPA-Lib"
    #updateJSONURL="http://myurl.me/"
    displayURL="https://github.com/lehjr/MPA-Lib"
    authors="MachineMuse, lehjr"
    description="A common library of useful functions and utilities for dealing with Minecraft's source code. Formerly known as Numina"

[[dependencies.mpalib]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mpalib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
