modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/lehjr/MPA-Lib/issues"

[[mods]]
    modId="@@mod_id@@"
    version="${version}"
    displayName="@@title@@" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional TODO
# A URL for the "homepage" for this mod, displayed in the mod UI
    displayURL="https://github.com/lehjr/MPA-Lib"
    authors="MachineMuse, lehjr"
    description="A common library of useful functions and utilities for dealing with Minecraft's source code. Formerly known as Numina"
[[dependencies.mpalib]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.mpalib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"